<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="AccountInformationService" targetNamespace="http://AccountInformationService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://AccountInformationService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="AccountInformationService_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="AccountInformationServiceHttpBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  
  
  
  
  <wsdl:types>
    <xsd:schema targetNamespace="http://AccountInformationService">
      <xsd:include schemaLocation="AccountInformationService_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="getBalanceRequestMsg">
    <wsdl:part element="tns:getBalance" name="getBalanceParameters"/>
  </wsdl:message>
  <wsdl:message name="getBalanceResponseMsg">
    <wsdl:part element="tns:getBalanceResponse" name="getBalanceResult"/>
  </wsdl:message>
    <wsdl:portType name="AccountInformationService">
    <wsdl:documentation/>
    <wsdl:operation name="getBalance">
      <wsdl:input message="tns:getBalanceRequestMsg" name="getBalanceRequest"/>
      <wsdl:output message="tns:getBalanceResponseMsg" name="getBalanceResponse"/>
    </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="AccountInformationServiceHttpBinding" type="tns:AccountInformationService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="getBalance">
      <soap:operation soapAction=""/>
      <wsdl:input name="getBalanceRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="getBalanceResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
    <wsdl:service name="AccountInformationServiceHttpService">
    <wsdl:port binding="tns:AccountInformationServiceHttpBinding" name="AccountInformationServiceHttpPort">
      <soap:address location="http://localhost:7080/AccountInformationService/AccountInformationService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>