<?xml version="1.0" encoding="UTF-8"?><wsdl:definitions name="AccountOpeningByPartnerService" targetNamespace="http://AccountOpeningByPartnerService" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:tns="http://AccountOpeningByPartnerService" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <wsdl:documentation>
    <wsdl:appinfo source="WMQI_APPINFO">
      <MRWSDLAppInfo imported="true">
        <generatedXSD location="AccountOpeningByPartnerService_InlineSchema1.xsd"/>
        <binding hasEncoding="false" imported="true" name="AccountOpeningByPartnerServiceHttpBinding" originalBindingStyle="document"/>
      </MRWSDLAppInfo>
    </wsdl:appinfo>
  </wsdl:documentation>
  
  <wsdl:types>
    <xsd:schema targetNamespace="http://AccountOpeningByPartnerService">
      <xsd:include schemaLocation="AccountOpeningByPartnerService_InlineSchema1.xsd"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="openRetailLoanAccountRequestMsg">
    <wsdl:part element="tns:openRetailLoanAccount" name="openRetailLoanAccountParameters"/>
  </wsdl:message>
  <wsdl:message name="openRetailLoanAccountResponseMsg">
    <wsdl:part element="tns:openRetailLoanAccountResponse" name="openRetailLoanAccountResult"/>
  </wsdl:message>
  <wsdl:portType name="AccountOpeningByPartnerService">
    <wsdl:operation name="openRetailLoanAccount">
      <wsdl:input message="tns:openRetailLoanAccountRequestMsg" name="openRetailLoanAccountRequest"/>
      <wsdl:output message="tns:openRetailLoanAccountResponseMsg" name="openRetailLoanAccountResponse"/>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="AccountOpeningByPartnerServiceHttpBinding" type="tns:AccountOpeningByPartnerService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="openRetailLoanAccount">
      <soap:operation soapAction="http://AccountOpeningByPartnerService/openRetailLoanAccount"/>
      <wsdl:input name="openRetailLoanAccountRequest">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="openRetailLoanAccountResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
    </wsdl:binding>
  <wsdl:service name="AccountOpeningByPartnerServiceHttpService">
    <wsdl:port binding="tns:AccountOpeningByPartnerServiceHttpBinding" name="AccountOpeningByPartnerServiceHttpPort">
      <soap:address location="http://localhost:7800/AccountOpeningByPartnerService/AccountOpeningByPartnerService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>